server.port=${SERVER_PORT}

spring.mongodb.uri=${DB_URL}

langchain4j.ollama.chat-model.base-url=${BASE_URL}
langchain4j.ollama.chat-model.model-name=${BASE_MODEL}
langchain4j.ollama.chat-model.temperature=${BASE_TEMPERATURE}

spring.data.mongodb.auto-index-creation=true

logging.level.org.mongodb.driver=warn
logging.level.com.example.linehaul=info